<a href="https://colab.research.google.com/github/XingxinHE/DEEP-LEARNING-WITH-PYTORCH-A-60-MINUTE-BLITZ/blob/main/00_tensor_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
%matplotlib inline


What is PyTorch?
================

PyTorch主要贡献在GPU加速，torch.tensor类似于Numpy的ndarray，但是前者可以在GPU 运行。



In [5]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [6]:
x = torch.empty(5, 3)
print(x)

tensor([[2.1426e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.4460e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


Construct a randomly initialized matrix:



In [7]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3621, 0.2229, 0.1542],
        [0.5551, 0.3349, 0.9047],
        [0.5326, 0.6143, 0.2591],
        [0.8933, 0.9068, 0.9659],
        [0.1864, 0.4277, 0.8034]])


创建一个未初始化的矩阵时，当时在分配的内存中的任何值都将作为初始值出现。这就是为啥torch.empty里面有nan这些东西，每个人都不一样，每次compute都不一样

Construct a matrix filled zeros and of dtype long:



In [8]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [9]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user

note: 搞不懂这有啥用😶



In [10]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.2962,  0.8315, -0.4547],
        [ 0.3214, -0.0442, -0.2107],
        [-0.1735, -0.2775,  0.2229],
        [-0.6412,  0.3076,  0.4567],
        [-1.3065, -1.4966, -0.7170]])


Get its size:



In [11]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations（tensor的运算）
---------------
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [12]:
print(x)
y = torch.rand(5, 3)
print(y)
print(x + y)

tensor([[ 1.2962,  0.8315, -0.4547],
        [ 0.3214, -0.0442, -0.2107],
        [-0.1735, -0.2775,  0.2229],
        [-0.6412,  0.3076,  0.4567],
        [-1.3065, -1.4966, -0.7170]])
tensor([[0.7431, 0.9973, 0.6863],
        [0.4448, 0.0082, 0.4884],
        [0.9892, 0.0385, 0.4413],
        [0.1406, 0.1248, 0.0162],
        [0.8821, 0.9030, 0.8956]])
tensor([[ 2.0393,  1.8288,  0.2316],
        [ 0.7662, -0.0360,  0.2777],
        [ 0.8157, -0.2390,  0.6642],
        [-0.5007,  0.4324,  0.4729],
        [-0.4244, -0.5936,  0.1786]])


Addition: syntax 2



In [13]:
print(torch.add(x, y))

tensor([[ 2.0393,  1.8288,  0.2316],
        [ 0.7662, -0.0360,  0.2777],
        [ 0.8157, -0.2390,  0.6642],
        [-0.5007,  0.4324,  0.4729],
        [-0.4244, -0.5936,  0.1786]])


Addition: providing an output tensor as argument



In [14]:
result = torch.empty(5, 3)
torch.add(x, y, out=result) #居然还可以这么写…out指定为一个变量
print(result)

tensor([[ 2.0393,  1.8288,  0.2316],
        [ 0.7662, -0.0360,  0.2777],
        [ 0.8157, -0.2390,  0.6642],
        [-0.5007,  0.4324,  0.4729],
        [-0.4244, -0.5936,  0.1786]])


Addition: in-place 有点overwrite的意思，就是把x的值写入到y里面



In [15]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 2.0393,  1.8288,  0.2316],
        [ 0.7662, -0.0360,  0.2777],
        [ 0.8157, -0.2390,  0.6642],
        [-0.5007,  0.4324,  0.4729],
        [-0.4244, -0.5936,  0.1786]])


❗❗❗<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>❗❗❗

    

You can use standard NumPy-like indexing with all bells and whistles!



In [16]:
print(x[:, 1])

tensor([ 0.8315, -0.0442, -0.2775,  0.3076, -1.4966])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:

这个我还真没用过，torch.view可以改写tensor的size和shape


In [17]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


简单来说，.view(-1, ￥)就是把tensor弄成￥个column，-1代表你不用管的意思；

以下我把16个东西，可以以column=2, column=4, column=8

In [18]:
x.view(-1,8)

tensor([[ 0.0749,  1.3154,  0.3759,  0.6409, -1.2063, -0.7052,  1.6043,  0.4970],
        [-0.3182, -0.8437,  0.1576,  1.2447,  0.3746, -1.4619,  0.3436, -0.1384]])

In [19]:
x.view(-1,4)

tensor([[ 0.0749,  1.3154,  0.3759,  0.6409],
        [-1.2063, -0.7052,  1.6043,  0.4970],
        [-0.3182, -0.8437,  0.1576,  1.2447],
        [ 0.3746, -1.4619,  0.3436, -0.1384]])

In [20]:
x.view(-1,2)

tensor([[ 0.0749,  1.3154],
        [ 0.3759,  0.6409],
        [-1.2063, -0.7052],
        [ 1.6043,  0.4970],
        [-0.3182, -0.8437],
        [ 0.1576,  1.2447],
        [ 0.3746, -1.4619],
        [ 0.3436, -0.1384]])

If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [21]:
x = torch.randn(1)
print(x)
print(x.item())  #这个在plotting loss值的时候常用

tensor([-0.1606])
-0.1605842113494873


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.


Converting a Torch Tensor to a NumPy Array
------------



In [22]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [23]:
#用.numpy()即可
b = a.numpy()   
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

以下代码证明了Tensor和它相对的Numpy连通的，改变其中一个，另外一个也会改变



In [24]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


反之亦然，改变numpy, ->tensor也会跟着变


In [25]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [26]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([0.8394], device='cuda:0')
tensor([0.8394], dtype=torch.float64)


In [28]:
torch.cuda.get_device_name(0)

'Tesla T4'